version: '3'

services:
  coffebreak-webapp-proxy:
    container_name: coffebreak-webapp-proxy
    image: coffebreak-webapp-proxy:latest
    build:
      context: .
      dockerfile: Dockerfile.proxy
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=coffeebreakpodcast.app,www.coffeebreakpodcast.app
      - LETSENCRYPT_HOST=coffeebreakpodcast.app,www.coffeebreakpodcast.app
      - LETSENCRYPT_EMAIL=valentin@valentinvalverde.com
    labels:
      - "traefik.enable=true"
      # add rule for www.coffeebreakpodcast.app and coffeebreakpodcast.app
      - "traefik.frontend.rule=Host:coffeebreakpodcast.app,www.coffeebreakpodcast.app"
    networks:
      - coffebreak
    external_links:
      - backend
    depends_on:
      - coffebreak-webapp
    links:
      - coffebreak-webapp
    restart: always

  coffebreak-webapp:
    container_name: coffebreak-webapp
    image: coffebreak-webapp:latest
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - PORT=4000
    expose:
      - 4000
    restart: unless-stopped

    networks:
      coffebreak:
        aliases:
          - coffebreak-webapp

networks:
  coffebreak:
    external: true



